import { Helmet } from "react-helmet-async";
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";

// TODO: Legal review by Florida real estate counsel and an RGPD-qualified Spanish counsel
// required before these Terms are considered final. Remove this notice once cleared.

const EFFECTIVE_DATE = "May 2026";
const CONTACT_EMAIL = "contact@carlosre.com";

export default function TermsPage() {
  return (
    <>
      <Helmet>
        <title>Terms of Use | HomesProfessional.com</title>
        <meta name="description" content="Terms of use for HomesProfessional.com — conditions governing use of this website and its services." />
        <link rel="canonical" href="https://homesprofessional.com/terms" />
        <meta property="og:image" content="https://homesprofessional.com/images/og-default.png" />
        <meta name="robots" content="noindex" />
      </Helmet>
      <main id="main-content" className="min-h-screen bg-white pb-20">
        <Navbar />
        <div className="mx-auto max-w-3xl px-6 py-20">
          <p className="font-mono text-[10px] uppercase tracking-[0.3em] text-gold">Legal</p>
          <h1 className="mt-4 font-serif text-4xl text-navy">Terms of Use</h1>
          <p className="mt-3 font-mono text-[10px] uppercase tracking-[0.2em] text-navy/70">Effective: {EFFECTIVE_DATE} · HomesProfessional.com</p>

          <div className="mt-10 space-y-10 font-sans text-base leading-relaxed text-navy/75">

            <section>
              <h2 className="font-serif text-2xl text-navy">1. Acceptance of terms</h2>
              <p className="mt-4">By accessing HomesProfessional.com, you agree to be bound by these Terms of Use. If you do not agree, please do not use this site. These terms govern your use of the website and any services offered through it, including advisory inquiry forms, the AI desk assistant, and downloadable materials.</p>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-navy">2. Nature of the site</h2>
              <p className="mt-4">This website provides general information about real estate advisory services offered by Carlos Uzcategui, Florida Licensed Realtor® SL705771, an associate at United Realty Group. Nothing on this site constitutes legal, tax, financial, or investment advice. Real estate transactions involve material risk; you should consult qualified professionals before making any property decision.</p>
              <p className="mt-4">Carlos Uzcategui is licensed to practice real estate in the State of Florida. He is not licensed to practice law in any jurisdiction. References to Spanish agencies, Madrid networks, or cross-border advisory reflect business relationships and referral arrangements — not legal practice or licensed advisory in Spain.</p>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-navy">3. MLS and listing data</h2>
              <p className="mt-4">Any listing data displayed on this site is sourced from the Miami and South Florida REALTORS® MLS and is deemed reliable but not guaranteed. Listing information is subject to change without notice. All listings are subject to prior sale, change, or withdrawal. Neither Carlos Uzcategui nor United Realty Group shall be liable for any inaccuracy in listing data.</p>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-navy">4. AI desk assistant</h2>
              <p className="mt-4">The AI assistant on this site is powered by Google Gemini and is provided for general informational purposes only. Responses generated by the AI assistant do not constitute professional real estate advice, do not create a client relationship, and should not be relied upon for any transaction decision. The AI assistant may make errors. Always verify material information with a licensed professional.</p>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-navy">5. No agency relationship</h2>
              <p className="mt-4">Submitting a form, sending a message, or using the AI assistant on this site does not create a buyer agency agreement, seller representation agreement, or any other agency relationship. A formal representation agreement must be signed before any agency relationship exists.</p>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-navy">6. Intellectual property</h2>
              <p className="mt-4">All content on this site — including text, design, and code — is the property of Carlos Uzcategui or licensed to him. You may not reproduce, distribute, or create derivative works from any site content without prior written permission.</p>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-navy">7. REALTOR® trademark notice</h2>
              <p className="mt-4">REALTOR® is a registered collective membership mark that identifies a real estate professional who is a member of the National Association of REALTORS® (NAR) and subscribes to its Code of Ethics. Carlos Uzcategui is a member of the Miami and South Florida REALTORS®, which is a member of NAR.</p>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-navy">8. Equal Housing Opportunity</h2>
              <p className="mt-4">Carlos Uzcategui and United Realty Group are committed to the Fair Housing Act. We do not discriminate on the basis of race, color, national origin, religion, sex, disability, familial status, or any other class protected by applicable law.</p>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-navy">9. Limitation of liability</h2>
              <p className="mt-4">To the fullest extent permitted by law, Carlos Uzcategui and United Realty Group shall not be liable for any indirect, incidental, or consequential damages arising from your use of this site or reliance on any information provided herein.</p>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-navy">10. Governing law</h2>
              <p className="mt-4">These terms are governed by the laws of the State of Florida. Any disputes shall be resolved in the courts of Broward County, Florida.</p>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-navy">11. Contact</h2>
              <p className="mt-4">Carlos Uzcategui · Florida Licensed Realtor® SL705771<br />
              United Realty Group · 15951 SW 41 St #700, Weston, FL 33331<br />
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-gold underline">{CONTACT_EMAIL}</a></p>
            </section>

          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
