export interface CityConfig {
  name: string;
  slug: string;
  bridgeCity: string;
  bridgeMlsArea?: string;
  metaTitle: string;
  metaDescription: string;
  marketParagraph: string;
}

export const CITY_CONFIGS: Record<string, CityConfig> = {
  weston: {
    name: "Weston",
    slug: "weston",
    bridgeCity: "Weston",
    metaTitle: "Weston Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Weston real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Weston property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Weston is one of South Florida's most stable master-planned communities, consistently ranked among Florida's safest cities. Demand is driven by domestic relocators, corporate executives, and LATAM families — particularly Venezuelan and Colombian buyers seeking quality school districts and gated community infrastructure. Inventory turnover is methodical: sellers who price accurately move quickly; those who overshoot face compounding days on market. Carlos Uzcategui has represented sellers across Weston and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  "pembroke-pines": {
    name: "Pembroke Pines",
    slug: "pembroke-pines",
    bridgeCity: "Pembroke Pines",
    metaTitle: "Pembroke Pines Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Pembroke Pines real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Pembroke Pines property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Pembroke Pines is a high-velocity residential market driven by first and second-time buyers, young families, and domestic migrants from higher-cost states. Single-family home demand consistently outpaces condominium absorption here. Sellers benefit from the city's proximity to major employment corridors while buyers are drawn to its school district performance and relative affordability within Broward. Carlos Uzcategui has represented sellers across Pembroke Pines and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  plantation: {
    name: "Plantation",
    slug: "plantation",
    bridgeCity: "Plantation",
    metaTitle: "Plantation Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Plantation real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Plantation property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Plantation is a mature, tree-lined Broward community with persistent demand from buyers seeking large lots and established neighborhoods within commuting distance of Fort Lauderdale and Miami. The market skews toward move-up buyers and professional families relocating from out of state or upgrading within South Florida. Sellers here compete on condition and pricing discipline — overpriced inventory accumulates days and ultimately closes below initial asking. Carlos Uzcategui has represented sellers across Plantation and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  miramar: {
    name: "Miramar",
    slug: "miramar",
    bridgeCity: "Miramar",
    metaTitle: "Miramar Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Miramar real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Miramar property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Miramar has evolved into a significant employment and residential hub, anchored by its proximity to the Miramar Park of Commerce and major healthcare institutions. Buyer demand skews toward Caribbean and Central American buyers, corporate relocators, and investors seeking Broward County rental inventory. New construction has introduced competitive pricing pressure on resale inventory. Carlos Uzcategui has represented sellers across Miramar and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  miami: {
    name: "Miami",
    slug: "miami",
    bridgeCity: "Miami",
    metaTitle: "Miami Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Miami real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Miami property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Miami is a global tier-one real estate market with sustained demand from domestic high earners, LATAM capital, and European investors — particularly post-2021 when net migration into Miami-Dade accelerated sharply. The market is heterogeneous: single-family neighborhoods operate on entirely different dynamics than the Brickell and Edgewater condominium corridors. Sellers in Miami benefit from genuine international buyer competition — but only when their listing reaches those buyers through institutional distribution channels. Carlos Uzcategui has represented sellers across Miami and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  "coral-gables": {
    name: "Coral Gables",
    slug: "coral-gables",
    bridgeCity: "Coral Gables",
    metaTitle: "Coral Gables Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Coral Gables real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Coral Gables property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Coral Gables is Miami's most established luxury residential market — a city of historic architecture, Mediterranean Revival streetscapes, and high-net-worth buyer profiles that include corporate executives, diplomats, and multi-generational LATAM families. The Gables operates at a premium to surrounding markets, and buyers here are typically represented by experienced agents with specific neighborhood knowledge. Carlos Uzcategui has represented sellers across Coral Gables and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  doral: {
    name: "Doral",
    slug: "doral",
    bridgeCity: "Doral",
    metaTitle: "Doral Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Doral real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Doral property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Doral is South Florida's most concentrated hub for Venezuelan and broader LATAM buyer activity — a market where international capital has been the primary demand driver for over a decade. Condominium and townhome inventory moves quickly when priced to market; single-family inventory in gated communities commands measurable premiums. Sellers in Doral who access international buyer channels through the Miami MLS achieve meaningfully better outcomes than those relying on local traffic alone. Carlos Uzcategui has represented sellers across Doral and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  kendall: {
    name: "Kendall",
    slug: "kendall",
    bridgeCity: "Kendall",
    metaTitle: "Kendall Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Kendall real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Kendall property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Kendall encompasses a broad swath of Miami-Dade's western residential corridor — family-oriented neighborhoods, strong school districts, and a buyer profile dominated by LATAM families, particularly Colombian, Venezuelan, and Argentine buyers. Inventory ranges from entry-level townhomes to luxury waterfront estates. Sellers benefit from consistent demand but must position carefully against active new construction in adjacent Doral and Homestead corridors. Carlos Uzcategui has represented sellers across Kendall and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  "fort-lauderdale": {
    name: "Fort Lauderdale",
    slug: "fort-lauderdale",
    bridgeCity: "Fort Lauderdale",
    metaTitle: "Fort Lauderdale Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Fort Lauderdale real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Fort Lauderdale property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Fort Lauderdale operates as South Florida's second-largest real estate market — a waterfront city with an active boating and marine lifestyle that drives premium demand for deepwater-access and Intracoastal inventory. Buyer profiles span domestic retirees, yacht owners, and international buyers drawn to the Las Olas corridor. The Las Olas and Victoria Park neighborhoods consistently outperform broader market trends. Carlos Uzcategui has represented sellers across Fort Lauderdale and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  hollywood: {
    name: "Hollywood",
    slug: "hollywood",
    bridgeCity: "Hollywood",
    metaTitle: "Hollywood Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Hollywood real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Hollywood property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Hollywood is an undervalued market relative to its geographic position between Miami and Fort Lauderdale — a dynamic that drives both investor acquisition activity and first-time buyer demand from buyers priced out of neighboring markets. The Hollywood Beach corridor and ArtsPark district have been attracting a younger, design-conscious buyer profile. Carlos Uzcategui has represented sellers across Hollywood and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  aventura: {
    name: "Aventura",
    slug: "aventura",
    bridgeCity: "Aventura",
    metaTitle: "Aventura Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Aventura real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Aventura property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Aventura is one of South Florida's most concentrated luxury condominium markets — a walkable urban grid anchored by the Aventura Mall corridor and the Intracoastal Waterway. Buyer demand is predominantly international: Venezuelan, Brazilian, Argentine, and Canadian buyers account for a substantial share of transactions. Condominiums here compete on floor, views, and building amenity stack. Carlos Uzcategui has represented sellers across Aventura and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  "miami-beach": {
    name: "Miami Beach",
    slug: "miami-beach",
    bridgeCity: "Miami Beach",
    metaTitle: "Miami Beach Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Miami Beach real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Miami Beach property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Miami Beach is a globally recognized real estate market with limited land supply and high concentration of international buyer demand across its distinct neighborhoods — South of Fifth, Sunset Harbour, Mid-Beach, and the Venetian Islands each carry their own micro-market dynamics. The luxury condominium and single-family market here operates on fundamentally different absorption patterns than the broader Miami market. Carlos Uzcategui has represented sellers across Miami Beach and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  homestead: {
    name: "Homestead",
    slug: "homestead",
    bridgeCity: "Homestead",
    metaTitle: "Homestead Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Homestead real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Homestead property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Homestead is South Florida's most affordable major residential market — a city experiencing consistent in-migration from buyers priced out of Miami-Dade proper, alongside agricultural and logistics industry employment growth. New construction has been the dominant product here, creating pricing pressure on resale inventory that requires strategic positioning. Carlos Uzcategui has represented sellers across Homestead and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  "boca-raton": {
    name: "Boca Raton",
    slug: "boca-raton",
    bridgeCity: "Boca Raton",
    metaTitle: "Boca Raton Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Boca Raton real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Boca Raton property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Boca Raton anchors the northern luxury corridor of South Florida — a market characterized by country club communities, high-income domestic relocators from the Northeast, and significant Canadian and European second-home buyer activity. The luxury single-family market here is consistently one of the most active in Palm Beach County. Carlos Uzcategui has represented sellers across Boca Raton and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  "coral-springs": {
    name: "Coral Springs",
    slug: "coral-springs",
    bridgeCity: "Coral Springs",
    metaTitle: "Coral Springs Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Coral Springs real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Coral Springs property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Coral Springs is Broward's most consistently ranked family community — a market where school district performance drives buyer decision-making as much as price. Demand is sustained by domestic relocators, Northeast transplants, and LATAM families seeking a suburban lifestyle within commuting range of Fort Lauderdale and Boca Raton employment. Carlos Uzcategui has represented sellers across Coral Springs and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  parkland: {
    name: "Parkland",
    slug: "parkland",
    bridgeCity: "Parkland",
    metaTitle: "Parkland Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Parkland real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Parkland property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Parkland is South Florida's most exclusive suburban enclave — a low-density, equestrian-adjacent community with some of the highest per-household incomes in Broward County. The buyer profile is almost exclusively high-net-worth: executives, professionals, and LATAM families seeking maximum privacy within a gated, low-traffic environment. Inventory is limited and turnover is low, which historically supports premium valuations for well-maintained properties. Carlos Uzcategui has represented sellers across Parkland and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  "miami-lakes": {
    name: "Miami Lakes",
    slug: "miami-lakes",
    bridgeCity: "Miami Lakes",
    metaTitle: "Miami Lakes Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Miami Lakes real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Miami Lakes property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Miami Lakes is a master-planned community with one of South Florida's most stable residential markets — a town built around a golf course and lake system that has attracted LATAM families for decades. Venezuelan, Cuban, and Colombian buyers form the core demand base here. Inventory turns faster in this market than its size suggests, driven by strong community identity and school district quality. Carlos Uzcategui has represented sellers across Miami Lakes and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  hallandale: {
    name: "Hallandale Beach",
    slug: "hallandale",
    bridgeCity: "Hallandale Beach",
    metaTitle: "Hallandale Beach Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Hallandale Beach real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Hallandale Beach property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Hallandale Beach sits at the intersection of Miami-Dade and Broward County — a unique market position that attracts buyers seeking coastal access at lower price points than Aventura directly to the south. The condominium market here has seen increased interest from Brazilian and Argentine buyers, as well as domestic retirees drawn to ocean-adjacent living. Carlos Uzcategui has represented sellers across Hallandale and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  "pompano-beach": {
    name: "Pompano Beach",
    slug: "pompano-beach",
    bridgeCity: "Pompano Beach",
    metaTitle: "Pompano Beach Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Pompano Beach real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Pompano Beach property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Pompano Beach has been one of South Florida's most active markets for renovation and repositioning activity — a coastal community where buyer demand for updated product has been creating measurable price separation from unrenovated inventory. Direct ocean access and Intracoastal frontage continue to command meaningful premiums. Carlos Uzcategui has represented sellers across Pompano Beach and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  sunrise: {
    name: "Sunrise",
    slug: "sunrise",
    bridgeCity: "Sunrise",
    metaTitle: "Sunrise Real Estate Market | Homes for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Sunrise real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Sunrise property with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Sunrise is a high-volume residential market anchored by the Sawgrass Mills retail corridor and major arena infrastructure. Buyer demand spans first-time buyers, investors seeking Broward County rentals, and domestic relocators attracted to highway access and suburban infrastructure. Carlos Uzcategui has represented sellers across Sunrise and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
  brickell: {
    name: "Brickell",
    slug: "brickell",
    bridgeCity: "Miami",
    bridgeMlsArea: "Brickell",
    metaTitle: "Brickell Miami Real Estate Market | Condos for Sale | Carlos Uzcategui Realtor®",
    metaDescription: "Live Brickell real estate market data from the Miami and South Florida REALTORS® MLS. Updated daily. List your Brickell condo with access to 93,000 REALTORS® and 200+ global portals. Carlos Uzcategui, Florida Realtor® SL705771, United Realty Group.",
    marketParagraph: "Brickell is Miami's primary urban financial district — a vertical market of high-rise condominiums with a buyer profile that skews toward young professionals, domestic investors, and Latin American buyers seeking a pied-à-terre in the U.S. financial capital of the hemisphere. Absorption velocity here is driven by developer pipeline, unit condition, and building amenity quality. Pre-construction and post-delivery inventory compete aggressively in this submarket. Carlos Uzcategui has represented sellers across Brickell and the broader South Florida corridor since 2001 — 25 years of direct transaction experience in this market.",
  },
};
